insert into _solution (comment, creation_datetime, last_modified_datetime, assignment_id, group_id, user_id)
values ('test solution', now(), now(), (select id from _assignment where title = 'test tytul'),
        (select id from _group where name = 'grupa 1'), (select id from _user where email = 'jan_kowalski@gmail.com')),
       ('test solution 2', now(), now(), (select id from _assignment where title = 'test tytul'),
        (select id from _group where name = 'grupa 1'),
        (select id from _user where email = 'anna_malinowska@gmail.com')),
       ('test solution 3', now(), now(), (select id from _assignment where title = 'test tytul 2'),
        (select id from _group where name = 'grupa 1'), (select id from _user where email = 'jan_kowalski@gmail.com')),
       ('test solution 4', now(), now(), (select id from _assignment where title = 'test tytul 2'),
        (select id from _group where name = 'grupa 1'),
        (select id from _user where email = 'anna_malinowska@gmail.com')),
       ('test solution 5', now(), now(), (select id from _assignment where title = 'test tytul 3'),
        (select id from _group where name = 'grupa 2'),
        (select id from _user where email = 'anna_malinowska@gmail.com')),
       ('test solution 6', now(), now(), (select id from _assignment where title = 'test tytul 3'),
        (select id from _group where name = 'grupa 2'),
        (select id from _user where email = 'zofia_danielska@gmail.com')),
       ('test solution 7', now(), now(), (select id from _assignment where title = 'test tytul 4'),
        (select id from _group where name = 'grupa 2'),
        (select id from _user where email = 'anna_malinowska@gmail.com')),
       ('test solution 8', now(), now(), (select id from _assignment where title = 'test tytul 4'),
        (select id from _group where name = 'grupa 2'),
        (select id from _user where email = 'zofia_danielska@gmail.com')),
       ('test solution 9', now(), now(), (select id from _assignment where title = 'test tytul 5'),
        (select id from _group where name = 'grupa 3'), (select id from _user where email = 'jan_kowalski@gmail.com')),
       ('test solution 10', now(), now(), (select id from _assignment where title = 'test tytul 5'),
        (select id from _group where name = 'grupa 3'),
        (select id from _user where email = 'zofia_danielska@gmail.com')),
       ('test solution 11', now(), now(), (select id from _assignment where title = 'test tytul 6'),
        (select id from _group where name = 'grupa 3'), (select id from _user where email = 'jan_kowalski@gmail.com')),
       ('test solution 12', now(), now(), (select id from _assignment where title = 'test tytul 6'),
        (select id from _group where name = 'grupa 3'),
        (select id from _user where email = 'zofia_danielska@gmail.com'));