name: Deploy to AWS

on:
  workflow_run:
    workflows: ["Publish Docker image"]
    types:
      - completed
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull Docker images
        run: sudo docker pull pioszymk/homework-just-click -a
      - name: Delete Old docker containers
        run: sudo docker image prune -f
      - name: Run Docker Containers
        run: sudo docker-compose up -d 