name: Deploy to AWS

on:
  workflow_run:
    workflows: ["Publish Docker image"]
    types:
      - completed
jobs:
  deploy:
    runs-on: self-hosted
    env:
      API_URL: ${{ secrets.API_URL }}
      REACT_APP_API_URL: ${{ secrets.API_URL }}
      MONGO_URL: ${{ secrets.MONGO_URL }}
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      CORS_URL: ${{ secrets.CORS_URL }}
      REACT_APP_CORS_URL: ${{ secrets.CORS_URL }}
      REACT_APP_MONGO_API_URL: ${{ secrets.MONGO_API_URL }}
    steps:
    - name: Debug Environment Variables
      run: |
        echo "API_URL: $API_URL"
        echo "REACT_APP_CORS_URL: $MONGO_URL
    - name: Pull Docker images
      run: sudo docker pull pioszymk/homework-just-click -a
    - name: Delete Old docker containers
      run: sudo docker image prune -f
    - name: Run Docker Containers
      run: sudo docker-compose up -d 