name: Deploy to AWS

on:
  workflow_run:
    workflows: ["Publish Docker image"]
    types:
      - completed
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Pull Docker images
      run: sudo docker pull pioszymk/homework-just-click -a
    - name: Delete Old docker containers
      run: sudo docker rm -f $(sudo docker ps -aq)  || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8082:8082 --name backend_mongo pioszymk/homework-just-click:backend_mongo
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name backend pioszymk/homework-just-click:backend
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:3000 --name frontend pioszymk/homework-just-click:frontend