name: Run tests

on:
  push:
    branches: [master, main]
  pull_request: 
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - run: mvn --batch-mode --update-snapshots verify 
        working-directory: ./Backend
      - run: mkdir staging && cp target/*.jar staging
        working-directory: ./Backend
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging

      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '20'
      # - run: npm ci
      #   working-directory: ./frontend
      # - run: npm test
      #    working-directory: ./frontend